version: '2'

services:
  graphql-server:
    build: ./server/
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: MongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: Passphrase