version: "3.7"
services:
  app:
    build: ./server/
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:${GQL_PORT}
    depends_on:
      - mongo
    environment: 
      - MONGO_DB=${MONGO_DB}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PWD=${MONGO_PWD}
      - PORT=${GQL_PORT}
      - SECRET_KEY=${SECRET_KEY}
  mongo:
    image: mongo
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data/db:/data/db
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PWD}
